version: 0.2

env:
  variables:
    FRAMEWORK_VERSION: '1.5.0'
    EIA_FRAMEWORK_VERSION: '1.3.1'
    CPU_PY3_VERSION: '3'
    CPU_INSTANCE_TYPE: 'ml.c4.xlarge'
    GPU_PY3_VERSION: '3'
    EIA_PY3_VERSION: '3'
    GPU_INSTANCE_TYPE: 'ml.p2.xlarge'
    EIA_ACCELERATOR_TYPE: 'ml.eia2.medium'
    LOCAL_BASE_REPO: 'pytorch-base'
    ECR_REPO: 'sagemaker-test'
    GITHUB_REPO: 'sagemaker-pytorch-serving-container'


phases:
  pre_build:
    commands:
      - start-dockerd
      - ACCOUNT=$(aws --region $AWS_DEFAULT_REGION sts --endpoint-url https://sts.$AWS_DEFAULT_REGION.amazonaws.com get-caller-identity --query 'Account' --output text)
      - PREPROD_IMAGE="$ACCOUNT.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPO"
      - PR_NUM=$(echo $CODEBUILD_SOURCE_VERSION | grep -o '[0-9]\+')
      - BUILD_ID="$(echo $CODEBUILD_BUILD_ID | sed -e 's/:/-/g')"
      - echo 'Pull request number:' $PR_NUM '. No value means this build is not from pull request.'

  build:
    commands:
      - tox -e flake8

      - cpu_dockerfile="Dockerfile.cpu"
      - gpu_dockerfile="Dockerfile.gpu"
      - eia_dockerfile="Dockerfile.eia"

      # build py3 image
      - build_dir="docker/$FRAMEWORK_VERSION/py$GPU_PY3_VERSION"
      - cp -r docker/build_artifacts/* $build_dir/
      - CPU_PY3_TAG="$FRAMEWORK_VERSION-cpu-py3-$BUILD_ID"
      - GPU_PY3_TAG="$FRAMEWORK_VERSION-gpu-py3-$BUILD_ID"
      - EIA_PY3_TAG="$EIA_FRAMEWORK_VERSION-eia-py3-$BUILD_ID"
      - build_cmd="docker build -f "$build_dir/$cpu_dockerfile" -t $PREPROD_IMAGE:$CPU_PY3_TAG $build_dir"
      - execute-command-if-has-matching-changes "$build_cmd" "test/" "docker/*" "buildspec.yml"
      - build_cmd="docker build -f "$build_dir/$gpu_dockerfile" -t $PREPROD_IMAGE:$GPU_PY3_TAG $build_dir"
      - execute-command-if-has-matching-changes "$build_cmd" "test/" "docker/*" "buildspec.yml"
      # PY2 not offered for EIA PyTorch
      - eia_build_dir="docker/$EIA_FRAMEWORK_VERSION/py$EIA_PY3_VERSION"
      - cp -r docker/build_artifacts/* $eia_build_dir/
      - docker build -f "$eia_build_dir/$eia_dockerfile" -t $PREPROD_IMAGE:$EIA_PY3_TAG $eia_build_dir

      # push images to ecr
      - $(aws ecr get-login --registry-ids $ACCOUNT --no-include-email --region $AWS_DEFAULT_REGION)
      - push_cmd="docker push $PREPROD_IMAGE:$CPU_PY3_TAG"
      - execute-command-if-has-matching-changes "$push_cmd" "test/" "docker/*" "buildspec.yml"
      - push_cmd="docker push $PREPROD_IMAGE:$GPU_PY3_TAG"
      - execute-command-if-has-matching-changes "$push_cmd" "test/" "docker/*" "buildspec.yml"
      - push_cmd="docker push $PREPROD_IMAGE:$EIA_PY3_TAG"
      - execute-command-if-has-matching-changes "$push_cmd" "test/" "docker/*" "buildspec.yml"

      # launch remote gpu instance
      - prefix='ml.'
      - instance_type=${GPU_INSTANCE_TYPE#"$prefix"}
      - create-key-pair
      - launch-ec2-instance --instance-type $instance_type --ami-name dlami-ubuntu

      # run cpu integration tests
      - py3_cmd="tox -e py36 -- test/integration/local --region $AWS_DEFAULT_REGION --docker-base-name $PREPROD_IMAGE --framework-version $FRAMEWORK_VERSION --py-version $CPU_PY3_VERSION --processor cpu --tag $CPU_PY3_TAG"
      - execute-command-if-has-matching-changes "$py3_cmd" "test/" "docker/*" "buildspec.yml"

      # run gpu integration tests
      - printf "$SETUP_CMDS" > $SETUP_FILE
      - py3_pytest_cmd="IGNORE_COVERAGE=- tox -e py36 test/integration/local --region $AWS_DEFAULT_REGION --docker-base-name $PREPROD_IMAGE --framework-version $FRAMEWORK_VERSION --py-version $GPU_PY3_VERSION --processor gpu --tag $GPU_PY3_TAG"
      - py3_cmd="remote-test --github-repo $GITHUB_REPO --test-cmd \"$py3_pytest_cmd\" --setup-file $SETUP_FILE --pr-number \"$PR_NUM\""
      - execute-command-if-has-matching-changes "$py3_cmd" "test/" "docker/*" "buildspec.yml"

      # run cpu sagemaker tests
      - py3_cmd="IGNORE_COVERAGE=- tox -e py36 -- test/integration/sagemaker --region $AWS_DEFAULT_REGION --docker-base-name $ECR_REPO --aws-id $ACCOUNT --framework-version $FRAMEWORK_VERSION --py-version $CPU_PY3_VERSION --processor cpu --instance-type $CPU_INSTANCE_TYPE --tag $CPU_PY3_TAG"
      - execute-command-if-has-matching-changes "$py3_cmd" "test/" "docker/*" "buildspec.yml"

      # run gpu sagemaker tests
      - py3_cmd="IGNORE_COVERAGE=- tox -e py36 -- test/integration/sagemaker --region $AWS_DEFAULT_REGION --docker-base-name $ECR_REPO --aws-id $ACCOUNT --framework-version $FRAMEWORK_VERSION --py-version $GPU_PY3_VERSION --processor gpu --instance-type $GPU_INSTANCE_TYPE --tag $GPU_PY3_TAG"
      - execute-command-if-has-matching-changes "$py3_cmd" "test/" "docker/*" "buildspec.yml"

      # run eia sagemaker tests
      - py3_cmd="IGNORE_COVERAGE=- tox -e py36 -- test/integration/sagemaker --region $AWS_DEFAULT_REGION --docker-base-name $ECR_REPO --aws-id $ACCOUNT --framework-version $EIA_FRAMEWORK_VERSION --py-version $EIA_PY3_VERSION --processor cpu --instance-type $CPU_INSTANCE_TYPE --accelerator-type $EIA_ACCELERATOR_TYPE --tag $EIA_PY3_TAG"
      - execute-command-if-has-matching-changes "$py3_cmd" "test/" "docker/*" "buildspec.yml"

    finally:
      # shut down remote gpu instance
      - cleanup-gpu-instances
      - cleanup-key-pairs

      # remove ecr image
      - aws ecr batch-delete-image --repository-name $ECR_REPO --region $AWS_DEFAULT_REGION --image-ids imageTag=$CPU_PY3_TAG
      - aws ecr batch-delete-image --repository-name $ECR_REPO --region $AWS_DEFAULT_REGION --image-ids imageTag=$GPU_PY3_TAG
      - aws ecr batch-delete-image --repository-name $ECR_REPO --region $AWS_DEFAULT_REGION --image-ids imageTag=$EIA_PY3_TAG
